[project]
name = "netports"
version = "0.6.2"
authors = [{ name="Vladimir Prusakov", email="vladimir.prusakovs@gmail.com" }]
description = "Python tools for managing ranges of VLANs, TCP/UDP ports, IP protocols, Interfaces"
readme = "README.rst"
license = { text="MIT" }
requires-python = ">=3.8"
keywords = ["networking", "port", "range", "tcp", "udp", "vlan", "ip", "interface"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Telecommunications Industry",
    "Topic :: System :: Networking",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Natural Language :: English",
]
[project.urls]
"Homepage" = "https://github.com/vladimirs-git/netports"
"Repository" = "https://github.com/vladimirs-git/netports"
"Bug Tracker" = "https://github.com/vladimirs-git/netports/issues"
"Download URL" = "https://github.com/vladimirs-git/netports/archive/refs/tags/0.6.2.tar.gz"
[tool.setuptools.packages.find]
include = ["netports"]
[tool.setuptools.package-data]
netports = ["py.typed"]
[project.optional-dependencies]
dev = [
    "dictdiffer ~= 0.9",
    "mypy < 1",
    "pylint == 2.13.9",
    "pytest ~= 7.2",
    "restructuredtext-lint ~= 1.4",
    "twine ~= 4.0",
]
