"""Params helpers"""
# ============================== longs ===============================
LONGS = [
    "ATM",
    "AppGigabitEthernet",
    "Bridge-Aggregation",
    "Bundle-Ether",
    "BundleEthernet",
    "Embedded-Service-Engine",
    "Ethernet",
    "FastEthernet",
    "Fddi",
    "GigabitEthernet",
    "HundredGigabitEthernet",
    "Loopback",
    "Management",
    "MgmtEth",
    "Multilink",
    "Port-channel",
    "Serial",
    "Ten-GigabitEthernet",
    "TenGigabitEthernet",
    "Trk",
    "Tunnel",
    "TwentyFiveGigE",
    "Virtual-Access",
    "Virtual-Template",
    "Vlan",
    "appgigabitethernet",
    "atm",
    "bridge-aggregation",
    "bundle-ether",
    "bundleethernet",
    "embedded-service-engine",
    "ethernet",
    "fastethernet",
    "fddi",
    "gigabitethernet",
    "hundredgigabitethernet",
    "loopback",
    "management",
    "mgmt",
    "mgmteth",
    "multilink",
    "port-channel",
    "serial",
    "ten-gigabitethernet",
    "tengigabitethernet",
    "trk",
    "tunnel",
    "tunnel-ip",
    "twentyfivegige",
    "virtual-access",
    "virtual-template",
    "vlan",
]
LONGS_IOS = [
    "ATM",
    "AppGigabitEthernet",
    "BundleEthernet",
    "Embedded-Service-Engine",
    "Ethernet",
    "FastEthernet",
    "Fddi",
    "GigabitEthernet",
    "HundredGigE",
    "Loopback",
    "Management",
    "Multilink",
    "Port-channel",
    "Serial",
    "TenGigabitEthernet",
    "Tunnel",
    "TwentyFiveGigE",
    "Virtual-Access",
    "Virtual-Template",
    "Vlan",
    "appgigabitethernet",
    "atm",
    "bundleethernet",
    "embedded-service-engine",
    "ethernet",
    "fastethernet",
    "fddi",
    "gigabitethernet",
    "hundredgige",
    "loopback",
    "management",
    "multilink",
    "port-channel",
    "serial",
    "tengigabitethernet",
    "tunnel",
    "twentyfivegige",
    "virtual-access",
    "virtual-template",
    "vlan",
]
LONGS_IOS_LOWER_TRUE = [
    "appgigabitethernet",
    "atm",
    "bundleethernet",
    "embedded-service-engine",
    "ethernet",
    "fastethernet",
    "fddi",
    "gigabitethernet",
    "hundredgige",
    "loopback",
    "management",
    "multilink",
    "port-channel",
    "serial",
    "tengigabitethernet",
    "tunnel",
    "twentyfivegige",
    "virtual-access",
    "virtual-template",
    "vlan",
]
LONGS_IOS_LOWER_FALE = [
    "ATM",
    "AppGigabitEthernet",
    "BundleEthernet",
    "Embedded-Service-Engine",
    "Ethernet",
    "FastEthernet",
    "Fddi",
    "GigabitEthernet",
    "HundredGigE",
    "Loopback",
    "Management",
    "Multilink",
    "Port-channel",
    "Serial",
    "TenGigabitEthernet",
    "Tunnel",
    "TwentyFiveGigE",
    "Virtual-Access",
    "Virtual-Template",
    "Vlan",
]
# ============================== shorts ==============================
SHORTS = [
    "Ap",
    "At",
    "BAGG",
    "BE",
    "Bu",
    "Em",
    "Eth",
    "FD",
    "Fa",
    "GE",
    "Gi",
    "Hu",
    "Lo",
    "Ma",
    "Mg",
    "Mu",
    "Po",
    "Se",
    "Te",
    "Trk",
    "Tu",
    "Twe",
    "V",
    "Vi",
    "Vlan",
    "Vt",
    "XGE",
    "ap",
    "at",
    "bagg",
    "be",
    "bu",
    "em",
    "eth",
    "fa",
    "fd",
    "ge",
    "gi",
    "hu",
    "lo",
    "ma",
    "mg",
    "mgmt",
    "mu",
    "po",
    "se",
    "te",
    "ti",
    "trk",
    "tu",
    "twe",
    "v",
    "vi",
    "vlan",
    "vt",
    "xge",
]
SHORTS_IOS = [
    "Ap",
    "At",
    "Bu",
    "Em",
    "Eth",
    "FD",
    "Fa",
    "Gi",
    "Hu",
    "Lo",
    "Ma",
    "Mu",
    "Po",
    "Se",
    "Te",
    "Tu",
    "Twe",
    "V",
    "Vi",
    "Vlan",
    "Vt",
    "ap",
    "at",
    "bu",
    "em",
    "eth",
    "fa",
    "fd",
    "gi",
    "hu",
    "lo",
    "ma",
    "mu",
    "po",
    "se",
    "te",
    "tu",
    "twe",
    "v",
    "vi",
    "vlan",
    "vt",
]
SHORTS_IOS_LOWER_TRUE = [
    "ap",
    "at",
    "bu",
    "em",
    "eth",
    "fa",
    "fd",
    "gi",
    "hu",
    "lo",
    "ma",
    "mu",
    "po",
    "se",
    "te",
    "tu",
    "twe",
    "v",
    "vi",
    "vlan",
    "vt",
]
SHORTS_IOS_LOWER_FALE = [
    "Ap",
    "At",
    "Bu",
    "Em",
    "Eth",
    "FD",
    "Fa",
    "Gi",
    "Hu",
    "Lo",
    "Ma",
    "Mu",
    "Po",
    "Se",
    "Te",
    "Tu",
    "Twe",
    "V",
    "Vi",
    "Vlan",
    "Vt",
]
# ========================== short_to_long ===========================
SHORT_TO_LONG = {
    "Ap": "AppGigabitEthernet",
    "At": "ATM",
    "BAGG": "Bridge-Aggregation",
    "BE": "Bundle-Ether",
    "Bu": "BundleEthernet",
    "Em": "Embedded-Service-Engine",
    "Eth": "Ethernet",
    "FD": "Fddi",
    "Fa": "FastEthernet",
    "GE": "GigabitEthernet",
    "Gi": "GigabitEthernet",
    "Hu": "HundredGigabitEthernet",
    "Lo": "Loopback",
    "Ma": "Management",
    "Mg": "MgmtEth",
    "Mu": "Multilink",
    "Po": "Port-channel",
    "Se": "Serial",
    "Te": "TenGigabitEthernet",
    "Trk": "Trk",
    "Tu": "Tunnel",
    "Twe": "TwentyFiveGigE",
    "V": "Vlan",
    "Vi": "Virtual-Access",
    "Vlan": "Vlan",
    "Vt": "Virtual-Template",
    "XGE": "Ten-GigabitEthernet",
    "mgmt": "mgmt",
    "ti": "tunnel-ip",
}
SHORT_TO_LONG_VALUE_LOW = {k: v.lower() for k, v in SHORT_TO_LONG.items()}
SHORT_TO_LONG_KEY_LOW = {k.lower(): v for k, v in SHORT_TO_LONG.items()}
SHORT_TO_LONG_ASR = {
    "Ap": "AppGigabitEthernet",
    "At": "ATM",
    "BE": "Bundle-Ether",
    "Bu": "BundleEthernet",
    "Em": "Embedded-Service-Engine",
    "Eth": "Ethernet",
    "FD": "Fddi",
    "Fa": "FastEthernet",
    "Gi": "GigabitEthernet",
    "Hu": "HundredGigE",
    "Lo": "Loopback",
    "Ma": "Management",
    "Mg": "MgmtEth",
    "Mu": "Multilink",
    "Po": "Port-channel",
    "Se": "Serial",
    "Te": "TenGigE",
    "Tu": "tunnel-ip",
    "Twe": "TwentyFiveGigE",
    "V": "Vlan",
    "Vi": "Virtual-Access",
    "Vlan": "Vlan",
    "Vt": "Virtual-Template",
    "ti": "tunnel-ip",
}
SHORT_TO_LONG_IOS = {
    "Ap": "AppGigabitEthernet",
    "At": "ATM",
    "Bu": "BundleEthernet",
    "Em": "Embedded-Service-Engine",
    "Eth": "Ethernet",
    "FD": "Fddi",
    "Fa": "FastEthernet",
    "Gi": "GigabitEthernet",
    "Hu": "HundredGigE",
    "Lo": "Loopback",
    "Ma": "Management",
    "Mu": "Multilink",
    "Po": "Port-channel",
    "Se": "Serial",
    "Te": "TenGigabitEthernet",
    "Tu": "Tunnel",
    "Twe": "TwentyFiveGigE",
    "V": "Vlan",
    "Vi": "Virtual-Access",
    "Vlan": "Vlan",
    "Vt": "Virtual-Template",
}
SHORT_TO_LONG_NXOS = {
    "Ap": "AppGigabitEthernet",
    "At": "ATM",
    "Bu": "BundleEthernet",
    "Em": "Embedded-Service-Engine",
    "Eth": "Ethernet",
    "FD": "Fddi",
    "Fa": "FastEthernet",
    "Gi": "GigabitEthernet",
    "Hu": "HundredGigE",
    "Lo": "loopback",
    "Ma": "Management",
    "Mu": "Multilink",
    "Po": "port-channel",
    "Se": "Serial",
    "Te": "TenGigabitEthernet",
    "Tu": "Tunnel",
    "Twe": "TwentyFiveGigE",
    "V": "Vlan",
    "Vi": "Virtual-Access",
    "Vlan": "Vlan",
    "Vt": "Virtual-Template",
    "mgmt": "mgmt",
}
SHORT_TO_LONG_H3C = {
    "Ap": "AppGigabitEthernet",
    "At": "ATM",
    "BAGG": "Bridge-Aggregation",
    "Bu": "BundleEthernet",
    "Em": "Embedded-Service-Engine",
    "Eth": "Ethernet",
    "FD": "Fddi",
    "Fa": "FastEthernet",
    "GE": "GigabitEthernet",
    "Gi": "GigabitEthernet",
    "Hu": "HundredGigE",
    "Lo": "Loopback",
    "Ma": "Management",
    "Mu": "Multilink",
    "Po": "Port-channel",
    "Se": "Serial",
    "Te": "Ten-GigabitEthernet",
    "Tu": "Tunnel",
    "Twe": "TwentyFiveGigE",
    "V": "Vlan",
    "Vi": "Virtual-Access",
    "Vlan": "Vlan-interface",
    "Vt": "Virtual-Template",
    "XGE": "Ten-GigabitEthernet",
}
SHORT_TO_LONG_HPC = {
    "Ap": "AppGigabitEthernet",
    "At": "ATM",
    "Bu": "BundleEthernet",
    "Em": "Embedded-Service-Engine",
    "Eth": "Ethernet",
    "FD": "Fddi",
    "Fa": "FastEthernet",
    "Gi": "GigabitEthernet",
    "Hu": "HundredGigE",
    "Lo": "Loopback",
    "Ma": "Management",
    "Mu": "Multilink",
    "Po": "Port-channel",
    "Se": "Serial",
    "Te": "TenGigabitEthernet",
    "Trk": "Trk",
    "Tu": "Tunnel",
    "Twe": "TwentyFiveGigE",
    "V": "Vlan",
    "Vi": "Virtual-Access",
    "Vlan": "Vlan",
    "Vt": "Virtual-Template",
}
# ========================== short_to_short ==========================
SHORT_TO_SHORT = {
    "Ap": "Ap",
    "At": "At",
    "BAGG": "BAGG",
    "BE": "BE",
    "Bu": "Bu",
    "Em": "Em",
    "Eth": "Eth",
    "FD": "FD",
    "Fa": "Fa",
    "GE": "Gi",
    "Gi": "Gi",
    "Hu": "Hu",
    "Lo": "Lo",
    "Ma": "Ma",
    "Mg": "Mg",
    "Mu": "Mu",
    "Po": "Po",
    "Se": "Se",
    "Te": "Te",
    "Trk": "Trk",
    "Tu": "Tu",
    "Twe": "Twe",
    "V": "V",
    "Vi": "Vi",
    "Vlan": "V",
    "Vt": "Vt",
    "XGE": "XGE",
    "mgmt": "mgmt",
    "ti": "ti",
}
SHORT_TO_SHORT_VALUE_LOW = {k: v.lower() for k, v in SHORT_TO_SHORT.items()}
SHORT_TO_SHORT_KEY_LOW = {k.lower(): v for k, v in SHORT_TO_SHORT.items()}
SHORT_TO_SHORT_ASR = {
    "Ap": "Ap",
    "At": "At",
    "BE": "BE",
    "Bu": "Bu",
    "Em": "Em",
    "Eth": "Eth",
    "FD": "FD",
    "Fa": "Fa",
    "Gi": "Gi",
    "Hu": "Hu",
    "Lo": "Lo",
    "Ma": "Ma",
    "Mg": "Mg",
    "Mu": "Mu",
    "Po": "Po",
    "Se": "Se",
    "Te": "Te",
    "Tu": "ti",
    "Twe": "Twe",
    "V": "Vlan",
    "Vi": "Vi",
    "Vlan": "Vlan",
    "Vt": "Vt",
    "ti": "ti",
}
SHORT_TO_SHORT_IOS = {
    "Ap": "Ap",
    "At": "At",
    "Bu": "Bu",
    "Em": "Em",
    "Eth": "Eth",
    "FD": "FD",
    "Fa": "Fa",
    "Gi": "Gi",
    "Hu": "Hu",
    "Lo": "Lo",
    "Ma": "Ma",
    "Mu": "Mu",
    "Po": "Po",
    "Se": "Se",
    "Te": "Te",
    "Tu": "Tu",
    "Twe": "Twe",
    "V": "Vlan",
    "Vi": "Vi",
    "Vlan": "Vlan",
    "Vt": "Vt",
}
SHORT_TO_SHORT_NXOS = {
    "Ap": "Ap",
    "At": "At",
    "Bu": "Bu",
    "Em": "Em",
    "Eth": "Eth",
    "FD": "FD",
    "Fa": "Fa",
    "Gi": "Gi",
    "Hu": "Hu",
    "Lo": "Lo",
    "Ma": "Ma",
    "Mu": "Mu",
    "Po": "Po",
    "Se": "Se",
    "Te": "Te",
    "Tu": "Tu",
    "Twe": "Twe",
    "V": "Vlan",
    "Vi": "Vi",
    "Vlan": "Vlan",
    "Vt": "Vt",
    "mgmt": "mgmt",
}
SHORT_TO_SHORT_H3C = {
    "Ap": "Ap",
    "At": "At",
    "BAGG": "BAGG",
    "Bu": "Bu",
    "Em": "Em",
    "Eth": "Eth",
    "FD": "FD",
    "Fa": "Fa",
    "GE": "GE",
    "Gi": "GE",
    "Hu": "Hu",
    "Lo": "Lo",
    "Ma": "Ma",
    "Mu": "Mu",
    "Po": "Po",
    "Se": "Se",
    "Te": "XGE",
    "Tu": "Tu",
    "Twe": "Twe",
    "V": "V",
    "Vi": "Vi",
    "Vlan": "Vlan",
    "Vt": "Vt",
    "XGE": "XGE",
}
SHORT_TO_SHORT_HPC = {
    "Ap": "Ap",
    "At": "At",
    "Bu": "Bu",
    "Em": "Em",
    "Eth": "Eth",
    "FD": "FD",
    "Fa": "Fa",
    "Gi": "Gi",
    "Hu": "Hu",
    "Lo": "Lo",
    "Ma": "Ma",
    "Mu": "Mu",
    "Po": "Po",
    "Se": "Se",
    "Te": "Te",
    "Trk": "Trk",
    "Tu": "Tu",
    "Twe": "Twe",
    "V": "Vlan",
    "Vi": "Vi",
    "Vlan": "Vlan",
    "Vt": "Vt",
}

# ========================== long_to_short ===========================
LONG_TO_SHORT = {
    "ATM": "At",
    "AppGigabitEthernet": "Ap",
    "Bridge-Aggregation": "BAGG",
    "Bundle-Ether": "BE",
    "BundleEthernet": "Bu",
    "Embedded-Service-Engine": "Em",
    "Ethernet": "Eth",
    "FastEthernet": "Fa",
    "Fddi": "FD",
    "GigabitEthernet": "Gi",
    "HundredGigE": "Hu",
    "HundredGigabitEthernet": "Hu",
    "Loopback": "Lo",
    "Management": "Ma",
    "MgmtEth": "Mg",
    "Multilink": "Mu",
    "Port-channel": "Po",
    "Serial": "Se",
    "Ten-GigabitEthernet": "XGE",
    "TenGigabitEthernet": "Te",
    "Trk": "Trk",
    "Tunnel": "Tu",
    "TwentyFiveGigE": "Twe",
    "Virtual-Access": "Vi",
    "Virtual-Template": "Vt",
    "Vlan": "V",
    "mgmt": "mgmt",
    "tunnel-ip": "ti",
}
LONG_TO_SHORT_VALUE_LOW = {k: v.lower() for k, v in LONG_TO_SHORT.items()}
LONG_TO_SHORT_KEY_LOW = {k.lower(): v for k, v in LONG_TO_SHORT.items()}
LONG_TO_SHORT_ASR = {
    "ATM": "At",
    "AppGigabitEthernet": "Ap",
    "Bundle-Ether": "BE",
    "BundleEthernet": "Bu",
    "Embedded-Service-Engine": "Em",
    "Ethernet": "Eth",
    "FastEthernet": "Fa",
    "Fddi": "FD",
    "GigabitEthernet": "Gi",
    "HundredGigE": "Hu",
    "HundredGigabitEthernet": "Hu",
    "Loopback": "Lo",
    "Management": "Ma",
    "MgmtEth": "Mg",
    "Multilink": "Mu",
    "Port-channel": "Po",
    "Serial": "Se",
    "TenGigE": "Te",
    "TenGigabitEthernet": "Te",
    "Tunnel": "ti",
    "TwentyFiveGigE": "Twe",
    "Virtual-Access": "Vi",
    "Virtual-Template": "Vt",
    "Vlan": "Vlan",
    "tunnel-ip": "ti",
}
LONG_TO_SHORT_IOS = {
    "ATM": "At",
    "AppGigabitEthernet": "Ap",
    "BundleEthernet": "Bu",
    "Embedded-Service-Engine": "Em",
    "Ethernet": "Eth",
    "FastEthernet": "Fa",
    "Fddi": "FD",
    "GigabitEthernet": "Gi",
    "HundredGigE": "Hu",
    "HundredGigabitEthernet": "Hu",
    "Loopback": "Lo",
    "Management": "Ma",
    "Multilink": "Mu",
    "Port-channel": "Po",
    "Serial": "Se",
    "TenGigabitEthernet": "Te",
    "Tunnel": "Tu",
    "TwentyFiveGigE": "Twe",
    "Virtual-Access": "Vi",
    "Virtual-Template": "Vt",
    "Vlan": "Vlan",
}
LONG_TO_SHORT_NXOS = {
    "ATM": "At",
    "AppGigabitEthernet": "Ap",
    "BundleEthernet": "Bu",
    "Embedded-Service-Engine": "Em",
    "Ethernet": "Eth",
    "FastEthernet": "Fa",
    "Fddi": "FD",
    "GigabitEthernet": "Gi",
    "HundredGigE": "Hu",
    "HundredGigabitEthernet": "Hu",
    "Loopback": "Lo",
    "Management": "Ma",
    "Multilink": "Mu",
    "Port-channel": "Po",
    "Serial": "Se",
    "TenGigabitEthernet": "Te",
    "Tunnel": "Tu",
    "TwentyFiveGigE": "Twe",
    "Virtual-Access": "Vi",
    "Virtual-Template": "Vt",
    "Vlan": "Vlan",
    "loopback": "Lo",
    "mgmt": "mgmt",
    "port-channel": "Po",
}
LONG_TO_SHORT_H3C = {
    "ATM": "At",
    "AppGigabitEthernet": "Ap",
    "Bridge-Aggregation": "BAGG",
    "BundleEthernet": "Bu",
    "Embedded-Service-Engine": "Em",
    "Ethernet": "Eth",
    "FastEthernet": "Fa",
    "Fddi": "FD",
    "GigabitEthernet": "GE",
    "HundredGigE": "Hu",
    "HundredGigabitEthernet": "Hu",
    "Loopback": "Lo",
    "Management": "Ma",
    "Multilink": "Mu",
    "Port-channel": "Po",
    "Serial": "Se",
    "Ten-GigabitEthernet": "XGE",
    "TenGigabitEthernet": "XGE",
    "Tunnel": "Tu",
    "TwentyFiveGigE": "Twe",
    "Virtual-Access": "Vi",
    "Virtual-Template": "Vt",
    "Vlan": "V",
    "Vlan-interface": "Vlan",
}
LONG_TO_SHORT_HPC = {
    "ATM": "At",
    "AppGigabitEthernet": "Ap",
    "BundleEthernet": "Bu",
    "Embedded-Service-Engine": "Em",
    "Ethernet": "Eth",
    "FastEthernet": "Fa",
    "Fddi": "FD",
    "GigabitEthernet": "Gi",
    "HundredGigE": "Hu",
    "HundredGigabitEthernet": "Hu",
    "Loopback": "Lo",
    "Management": "Ma",
    "Multilink": "Mu",
    "Port-channel": "Po",
    "Serial": "Se",
    "TenGigabitEthernet": "Te",
    "Trk": "Trk",
    "Tunnel": "Tu",
    "TwentyFiveGigE": "Twe",
    "Virtual-Access": "Vi",
    "Virtual-Template": "Vt",
    "Vlan": "Vlan",
}

# long_to_long
LONG_TO_LONG = {
    "ATM": "ATM",
    "AppGigabitEthernet": "AppGigabitEthernet",
    "Bridge-Aggregation": "Bridge-Aggregation",
    "Bundle-Ether": "Bundle-Ether",
    "BundleEthernet": "BundleEthernet",
    "Embedded-Service-Engine": "Embedded-Service-Engine",
    "Ethernet": "Ethernet",
    "FastEthernet": "FastEthernet",
    "Fddi": "Fddi",
    "GigabitEthernet": "GigabitEthernet",
    "HundredGigabitEthernet": "HundredGigabitEthernet",
    "Loopback": "Loopback",
    "Management": "Management",
    "MgmtEth": "MgmtEth",
    "Multilink": "Multilink",
    "Port-channel": "Port-channel",
    "Serial": "Serial",
    "Ten-GigabitEthernet": "Ten-GigabitEthernet",
    "TenGigabitEthernet": "TenGigabitEthernet",
    "Trk": "Trk",
    "Tunnel": "Tunnel",
    "TwentyFiveGigE": "TwentyFiveGigE",
    "Virtual-Access": "Virtual-Access",
    "Virtual-Template": "Virtual-Template",
    "Vlan": "Vlan",
    "mgmt": "mgmt",
    "tunnel-ip": "tunnel-ip",
}
LONG_TO_LONG_VALUE_LOW = {k: v.lower() for k, v in LONG_TO_LONG.items()}
LONG_TO_LONG_KEY_LOW = {k.lower(): v for k, v in LONG_TO_LONG.items()}
LONG_TO_LONG_ASR = {
    "ATM": "ATM",
    "AppGigabitEthernet": "AppGigabitEthernet",
    "Bundle-Ether": "Bundle-Ether",
    "BundleEthernet": "BundleEthernet",
    "Embedded-Service-Engine": "Embedded-Service-Engine",
    "Ethernet": "Ethernet",
    "FastEthernet": "FastEthernet",
    "Fddi": "Fddi",
    "GigabitEthernet": "GigabitEthernet",
    "HundredGigE": "HundredGigE",
    "Loopback": "Loopback",
    "Management": "Management",
    "MgmtEth": "MgmtEth",
    "Multilink": "Multilink",
    "Port-channel": "Port-channel",
    "Serial": "Serial",
    "TenGigE": "TenGigE",
    "TwentyFiveGigE": "TwentyFiveGigE",
    "Virtual-Access": "Virtual-Access",
    "Virtual-Template": "Virtual-Template",
    "Vlan": "Vlan",
    "tunnel-ip": "tunnel-ip",
}
LONG_TO_LONG_IOS = {
    "ATM": "ATM",
    "AppGigabitEthernet": "AppGigabitEthernet",
    "BundleEthernet": "BundleEthernet",
    "Embedded-Service-Engine": "Embedded-Service-Engine",
    "Ethernet": "Ethernet",
    "FastEthernet": "FastEthernet",
    "Fddi": "Fddi",
    "GigabitEthernet": "GigabitEthernet",
    "HundredGigE": "HundredGigE",
    "Loopback": "Loopback",
    "Management": "Management",
    "Multilink": "Multilink",
    "Port-channel": "Port-channel",
    "Serial": "Serial",
    "TenGigabitEthernet": "TenGigabitEthernet",
    "Tunnel": "Tunnel",
    "TwentyFiveGigE": "TwentyFiveGigE",
    "Virtual-Access": "Virtual-Access",
    "Virtual-Template": "Virtual-Template",
    "Vlan": "Vlan",
}
LONG_TO_LONG_NXOS = {
    "ATM": "ATM",
    "AppGigabitEthernet": "AppGigabitEthernet",
    "BundleEthernet": "BundleEthernet",
    "Embedded-Service-Engine": "Embedded-Service-Engine",
    "Ethernet": "Ethernet",
    "FastEthernet": "FastEthernet",
    "Fddi": "Fddi",
    "GigabitEthernet": "GigabitEthernet",
    "HundredGigE": "HundredGigE",
    "Management": "Management",
    "Multilink": "Multilink",
    "Serial": "Serial",
    "TenGigabitEthernet": "TenGigabitEthernet",
    "Tunnel": "Tunnel",
    "TwentyFiveGigE": "TwentyFiveGigE",
    "Virtual-Access": "Virtual-Access",
    "Virtual-Template": "Virtual-Template",
    "Vlan": "Vlan",
    "loopback": "loopback",
    "mgmt": "mgmt",
    "port-channel": "port-channel",
}
LONG_TO_LONG_H3C = {
    "ATM": "ATM",
    "AppGigabitEthernet": "AppGigabitEthernet",
    "Bridge-Aggregation": "Bridge-Aggregation",
    "BundleEthernet": "BundleEthernet",
    "Embedded-Service-Engine": "Embedded-Service-Engine",
    "Ethernet": "Ethernet",
    "FastEthernet": "FastEthernet",
    "Fddi": "Fddi",
    "GigabitEthernet": "GigabitEthernet",
    "HundredGigE": "HundredGigE",
    "Loopback": "Loopback",
    "Management": "Management",
    "Multilink": "Multilink",
    "Port-channel": "Port-channel",
    "Serial": "Serial",
    "Ten-GigabitEthernet": "Ten-GigabitEthernet",
    "Tunnel": "Tunnel",
    "TwentyFiveGigE": "TwentyFiveGigE",
    "Virtual-Access": "Virtual-Access",
    "Virtual-Template": "Virtual-Template",
    "Vlan": "Vlan",
    "Vlan-interface": "Vlan-interface",
}
LONG_TO_LONG_HPC = {
    "ATM": "ATM",
    "AppGigabitEthernet": "AppGigabitEthernet",
    "BundleEthernet": "BundleEthernet",
    "Embedded-Service-Engine": "Embedded-Service-Engine",
    "Ethernet": "Ethernet",
    "FastEthernet": "FastEthernet",
    "Fddi": "Fddi",
    "GigabitEthernet": "GigabitEthernet",
    "HundredGigE": "HundredGigE",
    "Loopback": "Loopback",
    "Management": "Management",
    "Multilink": "Multilink",
    "Port-channel": "Port-channel",
    "Serial": "Serial",
    "TenGigabitEthernet": "TenGigabitEthernet",
    "Trk": "Trk",
    "Tunnel": "Tunnel",
    "TwentyFiveGigE": "TwentyFiveGigE",
    "Virtual-Access": "Virtual-Access",
    "Virtual-Template": "Virtual-Template",
    "Vlan": "Vlan",
}
